addpath ../libs/cnsp_utils
addpath ../libs/cnsp_utils/cnd
addpath ../libs/mTRF-Toolbox_v2/mtrf
addpath ../libs/NoiseTools
addpath ../libs/eeglab
addpath ../libs/eeglab/plugins/firfilt
addpath ../libs/eeglab/plugins/dipfit
addpath ../libs/eeglab/plugins/clean_rawdata
addpath ../libs/eeglab/plugins
addpath ../libs/eeglab/functions/supportfiles
addpath ../libs/eeglab/functions/miscfunc
addpath ../libs/eeglab/functions/timefreqfunc
addpath ../libs/eeglab/functions/statistics
addpath ../libs/eeglab/functions/popfunc
addpath ../libs/eeglab/functions/studyfunc
addpath ../libs/eeglab/functions/guifunc
addpath ../libs/eeglab/functions/sigprocfunc
addpath ../libs/eeglab/functions
addpath ../libs/eeglab/functions/adminfunc
